FROM ubuntu:16.04

LABEL mantainer="Eloy Lopez <elswork@gmail.com>"

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    libfreetype6-dev \
    libpng12-dev \
    libzmq3-dev \
    pkg-config \
    python \
    python3 \
    python3-dev \
    python-pip \
    python3-pip \
    python3-setuptools \
    #python-pillow \
    #python-h5py \
    #python3-scipy \
    rsync \
    software-properties-common \
    unzip \
    git \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

#RUN curl -O https://bootstrap.pypa.io/get-pip.py && \
 #   python get-pip.py && \
  #  rm get-pip.py

 RUN pip3 install --upgrade pip && \
  pip3 --no-cache-dir install \
     ipykernel \
     jupyter \
     matplotlib \
     numpy \
     scipy \
     sklearn \
     pandas \     
     && \
     python3 -m ipykernel.kernelspec

# ADD tensorflow-1.3.0-cp27-none-linux_armv7l.whl .

RUN curl -O http://ci.tensorflow.org/view/Nightly/job/nightly-pi-python3/lastSuccessfulBuild/artifact/output-artifacts/tensorflow-1.6.0rc1-cp34-none-any.whl && \
mv tensorflow-1.6.0rc1-cp34-none-any.whl tensorflow-1.6.0rc1-py3-none-any.whl && \
pip3 --no-cache-dir install tensorflow-1.6.0rc1-py3-none-any.whl && \
rm -f tensorflow-1.6.0rc1-py3-none-any.whl

COPY jupyter_notebook_config.py /root/.jupyter/

# Copy sample notebooks.
COPY notebooks /notebooks

# Jupyter has issues with being run directly:
#   https://github.com/ipython/ipython/issues/7062
# We just add a little wrapper script.
COPY run_jupyter.sh /
RUN chmod +x /run_jupyter.sh

# TensorBoard
EXPOSE 6006
# IPython
EXPOSE 8888

WORKDIR "/notebooks"

CMD ["/run_jupyter.sh", "--allow-root"]
